import * as vscode from "vscode";
import {
  CATEGORY_LABELS,
  countBySeverity,
  fixesFor,
  SEVERITY_ORDER,
  type AnalysisReport,
  type CodeFix,
  type Finding,
} from "../engine/findings";
import { formatRing } from "../memory/graph";

export function renderMarkdown(report: AnalysisReport): string {
  const out: string[] = [];
  out.push(`# Architecture review — ${report.workspaceName}`);
  out.push("");
  out.push(`**Grade: ${report.grade}**`);
  out.push("");
  out.push(report.summary);
  out.push("");
  if (report.incompleteReason) {
    out.push(`> ⚠️ ${report.incompleteReason}`);
    out.push("");
  }

  const counts = countBySeverity(report.findings);
  const present = SEVERITY_ORDER.filter((s) => counts[s] > 0);
  if (present.length > 0) {
    out.push(
      `${report.findings.length} finding(s): ` +
        present.map((s) => `${counts[s]} ${s}`).join(", "),
    );
    out.push("");
  }

  if (report.graph && report.graph.nodes.length > 0) {
    const graph = report.graph;
    out.push("## Structure");
    out.push("");
    out.push(
      `${graph.nodes.length} ${graph.granularity === "file" ? "files" : "modules"}, ` +
        `${graph.edges.length} dependencies, ${graph.depth} layers deep.`,
    );
    out.push("");
    if (graph.cycles.length > 0) {
      out.push("**Circular dependencies**");
      out.push("");
      for (const cycle of graph.cycles.slice(0, 8)) out.push(`- ${formatRing(cycle)}`);
      out.push("");
    }
    const hubs = [...graph.nodes]
      .sort((a, b) => b.fanIn + b.fanOut - (a.fanIn + a.fanOut))
      .slice(0, 5)
      .filter((n) => n.fanIn + n.fanOut > 0);
    if (hubs.length > 0) {
      out.push("**Most connected**");
      out.push("");
      for (const hub of hubs) {
        out.push(`- \`${hub.id}\` — ${hub.fanIn} in, ${hub.fanOut} out, layer ${hub.layer}`);
      }
      out.push("");
    }
  }

  if (report.blueprint) {
    const blueprint = report.blueprint;
    out.push("## Target architecture");
    out.push("");
    out.push(blueprint.summary);
    out.push("");
    if (blueprint.moves.length > 0) {
      out.push("### What should move where");
      out.push("");
      for (const move of blueprint.moves) {
        out.push(`- **${move.what}**: \`${move.from}\` → \`${move.to}\` — ${move.why}`);
      }
      out.push("");
    }
    if (blueprint.stack.length > 0) {
      out.push("### Worth modernising");
      out.push("");
      out.push("| Concern | Today | Recommended | Why |");
      out.push("| --- | --- | --- | --- |");
      for (const upgrade of blueprint.stack) {
        out.push(
          `| ${cell(upgrade.concern)} | ${cell(upgrade.current)} | ${cell(upgrade.recommended)} | ${cell(upgrade.why)} |`,
        );
      }
      out.push("");
    }
  }

  if (report.scalability) {
    const s = report.scalability;
    out.push("## Scalability");
    out.push("");
    out.push(`**Target:** ${s.target}`);
    out.push("");
    out.push(`**Estimated current capacity:** ${s.estimatedCurrentCapacity}`);
    out.push("");
    if (s.assumptions.length > 0) {
      out.push("**Assumptions behind that estimate**");
      out.push("");
      for (const a of s.assumptions) out.push(`- ${a}`);
      out.push("");
    }
    if (s.bottlenecks.length > 0) {
      out.push("### Bottlenecks, most limiting first");
      out.push("");
      for (const b of s.bottlenecks) {
        out.push(`${b.rank}. **${b.component}** — ${b.why}`);
      }
      out.push("");
    }
    if (s.roadmap.length > 0) {
      out.push("### Remediation roadmap");
      out.push("");
      for (const phase of s.roadmap) {
        out.push(`#### ${phase.phase}`);
        out.push("");
        for (const action of phase.actions) out.push(`- ${action}`);
        out.push("");
        out.push(`_Expected capacity after this phase: ${phase.expectedCapacity}_`);
        out.push("");
      }
    }
  }

  if (report.findings.length > 0) {
    out.push("## Findings");
    out.push("");
    for (const severity of SEVERITY_ORDER) {
      const group = report.findings.filter((f) => f.severity === severity);
      if (group.length === 0) continue;
      out.push(`### ${capitalize(severity)} (${group.length})`);
      out.push("");
      for (const finding of group) {
        out.push(...renderFinding(finding, fixesFor(report, finding.id)));
      }
    }
  }

  const loose = report.fixes.filter((fix) => !fix.findingId);
  if (loose.length > 0) {
    out.push("## Other suggested changes");
    out.push("");
    for (const fix of loose) out.push(...renderFix(fix));
  }

  out.push("---");
  out.push("");
  out.push(
    `Generated by IronBase on ${new Date(report.generatedAt).toLocaleString()} using ${report.provider} (${report.model}). ` +
      "Capacity figures are theoretical estimates derived from the code, not measurements from a load test.",
  );
  out.push("");
  return out.join("\n");
}

function renderFinding(finding: Finding, fixes: CodeFix[]): string[] {
  const out: string[] = [];
  out.push(`#### ${finding.title}`);
  out.push("");
  out.push(
    `*${CATEGORY_LABELS[finding.category]}*${finding.effort ? ` · ${finding.effort} effort` : ""}`,
  );
  out.push("");
  out.push(finding.explanation);
  out.push("");
  out.push(`**Fix:** ${finding.recommendation}`);
  out.push("");
  if (finding.evidence.length > 0) {
    out.push("**Where:**");
    out.push("");
    for (const e of finding.evidence) {
      const anchor = e.startLine ? `#L${e.startLine}` : "";
      const label = e.startLine ? `${e.file}:${e.startLine}` : e.file;
      out.push(`- [${label}](${e.file}${anchor})`);
    }
    out.push("");
  }
  for (const fix of fixes) out.push(...renderFix(fix));
  return out;
}

/** A patch as a fenced diff, so it survives a paste into a PR or an issue. */
function renderFix(fix: CodeFix): string[] {
  const out: string[] = [];
  out.push(
    `**Patch — ${fix.title}** (\`${fix.file}${fix.startLine ? `:${fix.startLine}` : ""}\`)`,
  );
  out.push("");
  out.push(fix.rationale);
  out.push("");
  out.push("```diff");
  if (fix.kind !== "create" && fix.anchor) {
    for (const line of fix.anchor.split("\n")) {
      out.push(`${fix.kind === "insert-after" ? " " : "-"}${line}`);
    }
  }
  for (const line of fix.replacement.split("\n")) out.push(`+${line}`);
  out.push("```");
  out.push("");
  return out;
}

/** Escapes a value for a Markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ");
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

export async function exportReport(report: AnalysisReport): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0];
  const target = await vscode.window.showSaveDialog({
    title: "Export architecture review",
    defaultUri: folder
      ? vscode.Uri.joinPath(folder.uri, "ARCHITECTURE_REVIEW.md")
      : undefined,
    filters: { Markdown: ["md"] },
  });
  if (!target) return;

  await vscode.workspace.fs.writeFile(
    target,
    Buffer.from(renderMarkdown(report), "utf8"),
  );
  const open = await vscode.window.showInformationMessage(
    `Saved ${target.path.split("/").pop()}.`,
    "Open",
  );
  if (open === "Open") {
    await vscode.window.showTextDocument(await vscode.workspace.openTextDocument(target));
  }
}
