import * as vscode from "vscode";
import {
  CATEGORY_LABELS,
  countBySeverity,
  SEVERITY_ORDER,
  type AnalysisReport,
  type Finding,
} from "../engine/findings";

export function renderMarkdown(report: AnalysisReport): string {
  const out: string[] = [];
  out.push(`# Architecture review — ${report.workspaceName}`);
  out.push("");
  out.push(`**Grade: ${report.grade}**`);
  out.push("");
  out.push(report.summary);
  out.push("");
  if (report.incompleteReason) {
    out.push(`> ⚠️ ${report.incompleteReason}`);
    out.push("");
  }

  const counts = countBySeverity(report.findings);
  const present = SEVERITY_ORDER.filter((s) => counts[s] > 0);
  if (present.length > 0) {
    out.push(
      `${report.findings.length} finding(s): ` +
        present.map((s) => `${counts[s]} ${s}`).join(", "),
    );
    out.push("");
  }

  if (report.scalability) {
    const s = report.scalability;
    out.push("## Scalability");
    out.push("");
    out.push(`**Target:** ${s.target}`);
    out.push("");
    out.push(`**Estimated current capacity:** ${s.estimatedCurrentCapacity}`);
    out.push("");
    if (s.assumptions.length > 0) {
      out.push("**Assumptions behind that estimate**");
      out.push("");
      for (const a of s.assumptions) out.push(`- ${a}`);
      out.push("");
    }
    if (s.bottlenecks.length > 0) {
      out.push("### Bottlenecks, most limiting first");
      out.push("");
      for (const b of s.bottlenecks) {
        out.push(`${b.rank}. **${b.component}** — ${b.why}`);
      }
      out.push("");
    }
    if (s.roadmap.length > 0) {
      out.push("### Remediation roadmap");
      out.push("");
      for (const phase of s.roadmap) {
        out.push(`#### ${phase.phase}`);
        out.push("");
        for (const action of phase.actions) out.push(`- ${action}`);
        out.push("");
        out.push(`_Expected capacity after this phase: ${phase.expectedCapacity}_`);
        out.push("");
      }
    }
  }

  if (report.findings.length > 0) {
    out.push("## Findings");
    out.push("");
    for (const severity of SEVERITY_ORDER) {
      const group = report.findings.filter((f) => f.severity === severity);
      if (group.length === 0) continue;
      out.push(`### ${capitalize(severity)} (${group.length})`);
      out.push("");
      for (const finding of group) out.push(...renderFinding(finding));
    }
  }

  out.push("---");
  out.push("");
  out.push(
    `Generated by IronBase on ${new Date(report.generatedAt).toLocaleString()} using ${report.provider} (${report.model}). ` +
      "Capacity figures are theoretical estimates derived from the code, not measurements from a load test.",
  );
  out.push("");
  return out.join("\n");
}

function renderFinding(finding: Finding): string[] {
  const out: string[] = [];
  out.push(`#### ${finding.title}`);
  out.push("");
  out.push(
    `*${CATEGORY_LABELS[finding.category]}*${finding.effort ? ` · ${finding.effort} effort` : ""}`,
  );
  out.push("");
  out.push(finding.explanation);
  out.push("");
  out.push(`**Fix:** ${finding.recommendation}`);
  out.push("");
  if (finding.evidence.length > 0) {
    out.push("**Where:**");
    out.push("");
    for (const e of finding.evidence) {
      const anchor = e.startLine ? `#L${e.startLine}` : "";
      const label = e.startLine ? `${e.file}:${e.startLine}` : e.file;
      out.push(`- [${label}](${e.file}${anchor})`);
    }
    out.push("");
  }
  return out;
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

export async function exportReport(report: AnalysisReport): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0];
  const target = await vscode.window.showSaveDialog({
    title: "Export architecture review",
    defaultUri: folder
      ? vscode.Uri.joinPath(folder.uri, "ARCHITECTURE_REVIEW.md")
      : undefined,
    filters: { Markdown: ["md"] },
  });
  if (!target) return;

  await vscode.workspace.fs.writeFile(
    target,
    Buffer.from(renderMarkdown(report), "utf8"),
  );
  const open = await vscode.window.showInformationMessage(
    `Saved ${target.path.split("/").pop()}.`,
    "Open",
  );
  if (open === "Open") {
    await vscode.window.showTextDocument(await vscode.workspace.openTextDocument(target));
  }
}
